### ISSUE TITLE
Dex div zero error (price is zero?)

### ISSUE THREAD

**Issue by robby-dermody** [CounterpartyXCP/counterblockd#92]
```
2015-01-19-T13:31:07+0000:^[[1;41mERROR^[[1;0m:cache:x / 0
Traceback (most recent call last):
  File "/home/xcp/counterpartyd_build/dist/counterblockd/lib/cache.py", line 51, in cached_function
    result = func(*args, **kwargs)
  File "/home/xcp/counterpartyd_build/dist/counterblockd/lib/components/dex.py", line 286, in get_market_orders
    market_order['amount'] = D(order['give_remaining']) / D(price)
  File "/usr/lib/python2.7/decimal.py", line 1323, in __truediv__
    return context._raise_error(DivisionByZero, 'x / 0', sign)
  File "/usr/lib/python2.7/decimal.py", line 3872, in _raise_error
    raise error(explanation)
DivisionByZero: x / 0
```

Followed by:
```
2015-01-19-T13:31:07+0000:^[[1;41mERROR^[[1;0m:cache:'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/xcp/counterpartyd_build/dist/counterblockd/lib/cache.py", line 51, in cached_function
    result = func(*args, **kwargs)
  File "/home/xcp/counterpartyd_build/dist/counterblockd/lib/components/dex.py", line 540, in get_market_details
    for order in market_orders:
TypeError: 'NoneType' object is not iterable
```

**Comment by ouziel-slama** [comment]
fixed
